# Generated by Django 2.1.7 on 2019-02-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puser',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=30)),
                ('bdate', models.DateTimeField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
