# Generated by Django 2.1.7 on 2019-02-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100000)),
                ('designation', models.CharField(max_length=10000)),
                ('points', models.IntegerField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('province', models.CharField(max_length=100)),
                ('region_1', models.CharField(max_length=100)),
                ('region_2', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('winery', models.CharField(max_length=100)),
            ],
        ),
    ]
